version: '2'
exclude_patterns:
  - '**/*graphql.ts'
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - 'src/server/mail/templates/**/*'
  plugins:
    fixme:
      enabled: true
    eslint:
      enabled: true
    
