version: '3.7'

services:
  vaken:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
      - 8081:8081
    stdin_open: true
    restart: on-failure
    volumes:
      - ./src:/usr/app/src
      - ./dist:/usr/app/dist
    environment:
      - PORT
      - SESSION_SECRET
      - GOOGLE_CALLBACK_URL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GITHUB_CALLBACK_URL
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - BUCKET_NAME
      - GCP_STORAGE_SERVICE_ACCOUNT
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - MSFT_CLIENT_ID
      - MSFT_CLIENT_SECRET
      - MSFT_REDIRECT_URL
      - CALENDARID
      - ALGOLIA_API_KEY





