# build environment
FROM node:14.15.3-alpine
RUN mkdir /usr/app/
WORKDIR /usr/app/

COPY . /usr/app/

RUN npm install
RUN npm install -g webpack webpack-cli typescript ts-node

CMD ["npm", "run", "dev"]