version: '3'

services:
  server:
    build: .
    env_file:
      - .env
    expose:
      - ${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}
      MONGO_BASE_URL: mongodb://mongodb:27017
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./src:/usr/src/app/src:ro
    depends_on:
      - mongodb
    command: npm run dev-server

  client:
    build: .
    env_file:
      - .env
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    command: npm start

  mongodb:
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - ./dist/data/db:/data/db
    expose:
      - ${MONGO_PORT}
    command: mongod --smallfiles --logpath=/dev/null
