name: LabelOnApproved
on: [pull-request]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          LABEL_NAME: 'approved'
          APPROVALS: '1'
