name: Stats
on:
  # Trigger the workflow on push to the main branch of pull request
  push:
    branches:
      - main
jobs:
  report:
    name: report webpack stats to packtracker.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: packtracker/report@2.2.7
        env:
          PT_PROJECT_TOKEN: ${{ secrets.PT_PROJECT_TOKEN }}
          WEBPACK_CONFIG_PATH: ./webpack.prod.js
  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm audit --audit-level=high --only=prod
